### PR TITLE
Run tests on GitHub Actions

### PR DESCRIPTION
**Pull request by chrismytton**
~~Once #16 has been merged the tests on `master` will be passing again. At that point we can rebase this pull request onto `master` so that the tests are run via GitHub Actions.~~

The tests on `master` are failing currently, so the failures on this pull request are expected.

### CODE REVIEW

**Comment by SimKennedy** [comment]
Hi @chrismytton , great to see github tests working! I'm a little confused by your description though..? 
The base for this PR is  `add-contracts-finder-data` , but you mention rebasing on master _after_ merging that (#16 ) into master. 
Since we're still working on #16 and this looks finished(?), is there any reason not to just merge this into `master` so tests are working there and then merge master in #16 so we can get #16 up to date and make sure tests are passing _before_ we merge #16?

**Comment by chrismytton** [comment]
@SimKennedy Originally this pull request was targeting master, but the tests were failing. I switched the target to #16 to get the tests passing again. This is because in my mind tests failing == no merge. But thinking about it, getting this change merged now probably makes sense. As you say that would mean you can get the tests passing before you merge 🙂 

I'll switch the base branch back to `master` and request a review.

**Comment by SimKennedy** [comment]
@chrismytton I get you. Ok, that sounds good. It would be nice to know master is passing tests before we merge #16. 👍

**Comment by SimKennedy** [comment]
BTW, I noticed you merged the this PR #19  and #18  into `master` branch using `rebase` method. 
Is this a preferred way to merge by you and `mysociety`? @zarino?

We at SN are used to doing "Merge commits" most of the time, mainly as this makes it easier to fix things and to see where branches were "branched" from and merged in when you look back over history, and means the commits within a branch can be seen in context of the branch. 

Happy to discuss a convention for us going forward, or just work with a combination if everyone is happy.

**Comment by chrismytton** [comment]
> We at SN are used to doing "Merge commits" most of the time, mainly as this makes it easier to fix things and to see where branches were "branched" from and merged in when you look back over history, and means the commits within a branch can be seen in context of the branch.

@SimKennedy I don't have a strong preference either way, so I'm happy to do merge commits from now on for consistency 👍

**Pull request merged**
