### PR TITLE
Move templates and styles into bluetail app

### PR DESCRIPTION
**Pull request by zarino**
* Move templates and styles into bluetail app
* Simplify bootstrap sass pipeline
* Remove old "prototype" templates

@SimKennedy let me know if I’ve missed anything!

### CODE REVIEW

**Comment by SimKennedy** [comment]
@zarino I've just cleared my local files and run a `script/setup` and get an error visiting the home page on my local server
```
CompilerError at /tenders/

<filter object at 0x110afc208> exit code 1
b'sassc: error: Error: File to import not found or unreadable: bootstrap.\n       Parent style sheet: /Users/sim/git/mysociety/bluetail/static/sass/main.scss\n        on line 7 of main.scss\n>> @import "bootstrap";\n   ^\n\n'
```

**Comment by zarino** [comment]
Sorry @SimKennedy I’d missed out a change to `main.scss`. I’ve fixed up that last commit – can you try it now?

**Comment by SimKennedy** [comment]
This is working now and looks good.
I noticed we still have a few files outside bluetail that would break things if the bluetail app was copied into a new django project. 

- `data` dir (I will move this into the bluetail dir)
- `web` 
- `templates`
- `vendor`

As far as I can see the `vendor` dir path is only referenced in the `settings.py` so we could just change the path of the gitsubmodule clone and update settings.py?

I guess the web/templates are common files with Silvereye? Perhaps these could be moved into the `bluetail` app for now as currently silvereye depends on `bluetail` ocds_models for the metrics anyway. 

I think the aim is to make things as seamless as possible between the `cove-ocds` re-styling for file submisison with the bluetail/silvereye metrics work in the `bluetail` repo, but the styling is not my domain so welcome thoughts from @chrismytton and could be considered in PR #37.

**Comment by zarino** [comment]
> I noticed we still have a few files outside bluetail that would break things if the bluetail app was copied into a new django project.

Feel free to move more stuff out of the project level, into the bluetail app. I left `base.html`, `site-header.html` etc in the project scope, because I’m not sure they’re _strictly_ bluetail-specific? Feels like they‘re just the "site" that the bluetail and silvereye "apps" slot into, so therefore something _separate_ to the two apps?

Not sure where to make the cut regarding the vendor directory. Yes, the bluetail styles and templates have a dependency on bootstrap, so maybe bootstrap belongs inside the bluetail app, rather than at the project level. But at the same time, both silvereye and the `base.html` / `site-header.html` templates mentioned above, also depend on bootstrap – so bootstrap clearly isn’t a bluetail _only_ thing. Meh, I’m not a Django expert, so I don’t know how this tension is usually resolved! Maybe @chrismytton might have a more experienced opinion.

**Comment by chrismytton** [comment]
I think for this specific case it makes sense to simply make two copies of the common templates and stylesheets. One for bluetail and one for silvereye. The fact that they share a codebase currently is just convenience more than anything. They should be considered two separate independent projects.

**Comment by SimKennedy** [comment]
@chrismytton That's probably a sensible approach, but it's worth considering there's more than the templates in common. The models for the OCDS tables and currently the sample data too is being shared. 
Since this PR is focused on bluetail though I think it will help to get the static/templates stuff "app-centric" as opposed to being in the root project, then we can see what needs sharing/moving.
I've created a PR (#44) for moving the other files in so it's clear to see what I mean. Let me know what you think.

**Pull request merged**
