### PR TITLE
Silvereye publisher metrics

### PR DESCRIPTION
**Pull request by SimKennedy**
Add basic PublisherMetrics model and mgmt cmd update_publisher_metrics to populate the metrics table using sql in silvereye/metrics/sql dir

### CODE REVIEW

**Comment by chrismytton** [comment]
@SimKennedy I'm getting the error below when running the `script/manage update_publisher_metrics` command. I've done a fresh `script/setup` using the latest `master` but still getting the same error. Any idea what's going on?

```
$ script/manage update_publisher_metrics
Executing metric sql from file /Users/chris/Code/mysociety/bluetail_root/bluetail/silvereye/metrics/sql/total_tenders.sql
Traceback (most recent call last):
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.CardinalityViolation: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script/../manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/chris/Code/mysociety/bluetail_root/bluetail/silvereye/management/commands/update_publisher_metrics.py", line 29, in handle
    cursor.execute(sql)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/chris/Code/mysociety/bluetail_root/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

**Comment by SimKennedy** [comment]
@chrismytton , this seems to be an issue with the anonymisation giving multiple names for the same ID.. We might need to be smarter about matching IDs to Fake buyer names for consisteny.
image

**Comment by chrismytton** [comment]
Have merged https://github.com/mysociety/bluetail/pull/37 into this PR so everything is in one place.

**Comment by chrismytton** [comment]
Going to force-pushing this branch a bit now while I tidy things up. Then going to move the silvereye bits over to [cove-ocds](https://github.com/spendnetwork/cove-ocds).

**Comment by chrismytton** [comment]
Have fixed the merge conflicts and merged in the latest master, so I think this is ready to go.

**Pull request merged**
